### ISSUE TITLE
Add custom styles

### ISSUE THREAD

**Issue by tedypranolo** [andypf/json-viewer#6] opened 2024-07-05 10:24 UTC
It would be nice if we can pass additional styles to the json viewer.
Because everything is rendered under a shadow-root, I couldn't make regular css style work.

**Comment by andypf** [comment] 2024-07-10 06:49
The inability to override styles is by design. However, it is possible to completely override the colors.

```json
{
  "--base00": "#101112",
  "--base01": "#1C1E1F",
  "--base02": "#26282A",
  "--base03": "#323639",
  "--base04": "#868A8E",
  "--base05": "#9DA0A2",
  "--base06": "#D2D5D7",
  "--base07": "#F1F2F3",
  "--base08": "#EF5253",
  "--base09": "#E66B2B",
  "--base0A": "#E4B51C",
  "--base0B": "#7CC844",
  "--base0C": "#52CBB0",
  "--base0D": "#33A3DC",
  "--base0E": "#A363D5",
  "--base0F": "#D73C9A"
}
```

For example: 
```html
<andypf-json-viewer theme='{"--base00": "#101112", "--base01": "#1C1E1F", "--base02": "#26282A", "--base03": "#323639", "--base04": "#868A8E", "--base05": "#9DA0A2", "--base06": "#D2D5D7", "--base07": "#F1F2F3", "--base08": "#EF5253", "--base09": "#E66B2B", "--base0A": "#E4B51C", "--base0B": "#7CC844", "--base0C": "#52CBB0", "--base0D": "#33A3DC", "--base0E": "#A363D5", "--base0F": "#D73C9A"}'>
  { "string": "this is a test ...", "integer": 42, "array":[ 1, 2, 3, "test",
  NaN], "float":3.14159, "string_number":"1234", "date": "Tue, Oct 17, 2023,
  08:58 AM" }
</andypf-json-viewer>
```

Here is the definition of variables:
--base00: Default Background
--base01 (unused): Lighter Background (Reserved for status bars, line numbers, and folding marks)
--base02: Borders and Background for types NaN, null, and undefined
--base03 (unused): Comments, Invisibles, Line Highlighting
--base04: Item Size
--base05: Default Foreground, Brackets, and Colons
--base06 (unused): Light Foreground (Infrequently used)
--base07: Keys, Colons, and Brackets
--base08: Color for NaN
--base09: Ellipsis and String Values
--base0A: Regular Expressions and Null Values
--base0B: Floating-Point Values
--base0C: Number Keys
--base0D: Icons, Search Input, Date
--base0E: Booleans and Expanded Icons
--base0F: Integers

**Comment by andypf** [comment] 2024-07-10 07:31
I've updated the Readme:
https://www.npmjs.com/package/@andypf/json-viewer#customizations

**Comment by tedypranolo** [comment] 2024-07-12 07:16
Thanks for the reply. Actually what I want to do is override the style of the copy button, it currently causes the content to be resized when the button is visible on hover.

**Comment by andypf** [comment] 2024-11-28 07:38
Closing this issue for now as it’s not a priority at the moment. However, it remains a valid idea and could be revisited in the future if needed.

**Closed by andypf** 2024-11-28 07:38 UTC
